# Generated by Django 5.2.4 on 2025-08-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_tree.familytree'),
        ),
    ]
