# Generated by Django 5.2.4 on 2025-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribe', models.CharField(max_length=100)),
                ('foods', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('traditions', models.TextField(blank=True)),
                ('banner_photo', models.ImageField(blank=True, null=True, upload_to='family_banners/')),
                ('additional_notes', models.TextField(blank=True)),
            ],
        ),
    ]
